<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Create Project' => 'en_Create Project',
    'Delete' => '',
    'ID' => '',
    'Projects' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Project: {name}' => '',
    'Ідентифікатор користувача, який створив проект' => '',
    'Версія запису' => '',
    'Дата завершення роботи над проектом' => '',
    'Дата оновлення проекту' => '',
    'Дата початку роботи над проектом' => '',
    'Дата створення проетку' => '',
    'Назва проекту' => '',
    'Опис проекту' => '',
    'Статус проекту' => '',
];
